// Optimization todos:
//  - Consider swapping Nodes with a HashSet<> which will be faster when removing nodes.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Reflection;
using System.Reflection.Emit;
using System.Text;
using GrEmit;
using JetBrains.Annotations;
using Lattice.Base;
using Lattice.Nodes;
using Lattice.Utils;
using Unity.Assertions;
using Unity.Entities;
using Unity.Profiling;
using Debug = UnityEngine.Debug;
using Type = System.Type;

// Compiles all LatticeGraphs into a single global IR representation. 
// We run this all at once in a blast, like a standard all-at-once compiler. Eventually we may want to make it
// incremental instead. But for now it should be plenty fast.

namespace Lattice.IR
{
    /// <summary>Calculated properties for each node, propagated through the graph after it is constructed.</summary>
    public class Metadata
    {
        /// <summary>If the node had a compilation error, marked here. Propagated to children.</summary>
        [CanBeNull]
        public NodeCompilationError CompilationError;

        /// <summary>If the node is static or keyed by entity.</summary>
        public Qualifier? Qualifier;

        /// <summary>The type of the output value of the node.</summary>
        public Type OutputType;

        /// <summary>Executions of this node are guaranteed to run *after* this system executes.</summary>
        public Type ExecutionPhase;

        public Metadata(Qualifier? qualifier, Type outputType, Type executionPhase,
                        NodeCompilationError compilationError = null)
        {
            CompilationError = compilationError;
            Qualifier = qualifier;
            OutputType = outputType;
            ExecutionPhase = executionPhase;
        }
    }

    public class GraphCompilation
    {
        private const bool Verbose = false;

        /// <summary>The compiler configuration that generated this compilation.</summary>
        public GraphCompiler.Settings Settings;

        /// <summary>If true, the graph is invalid enough that we shouldn't try to execute it.</summary>
        public bool CannotBeExecuted;

        /// <summary>Set to true after the compiler does its high level analysis like type checking.</summary>
        public bool AnalysisFinished;

        /// <summary>Controls how profile markers are emitted in the generated code.</summary>
        public readonly ProfileMarkerGranularity ProfileMarkerOptions = ProfileMarkerGranularity.IrNode;

        // The main graph for this compilation. Inlines all top-level lattice graphs within it. 
        public IRGraph Graph = new();

        // The graphs that are manually added at the start of compilation.
        // The set of graphs that are mounted as subgraphs in the top-level graph. 
        public HashSet<LatticeGraph> TopLevelGraphs = new();

        // The fully-inlined IR for each LatticeGraph that is a part of this compilation.
        private readonly Dictionary<LatticeGraph, IRGraph> GraphBodies = new();

        // The entity nodes we create in the top-level graph, one for each top level graph.
        private readonly Dictionary<LatticeGraph, EntityIRNode> EntityNodes = new();

        /// <summary>Metadata for a node, generated by compiling the graph (a light form of execution without qualifiers).</summary>
        public readonly Dictionary<IRNode, Metadata> MetadataDb = new();

        // The set of qualifiers in the compilation.
        private HashSet<Qualifier> allQualifiers;

        // Whether the node is used by another work unit. Lazily generated.
        private HashSet<IRNode> referencedByAnotherWorkUnit;

        // Work units are larger groups of nodes that will be executed on a single thread.
        // If null, the graph is not yet partitioned. Once this is set, it's immutable, although we could probably allow mutation.
        internal Dictionary<IRNode, WorkUnit> WorkUnitForNode;
        internal List<WorkUnit> WorkUnitsTopological;
        internal Dictionary<WorkUnit, ILGeneration.ExecuteGraph> WorkUnitDelegates;

        // Stored in topological order.
        internal Dictionary<Type, List<WorkUnit>> WorkUnitsInPhase;

        /// <summary>A container type that stores all of the IL generated methods used for FunctionIRNodes during construction.</summary>
        private readonly TypeBuilder generatedFunctionNodes;

        /// <summary>Contains all the generated code for the graph, in the dynamic assembly. </summary>
        internal readonly ModuleBuilder CodeGenModule;

        /// <summary>Contains all the generated code for the graph, in the dynamic assembly. </summary>
        internal readonly AssemblyBuilder CodeGenAssembly;

        /// <summary>
        ///     We cache generated method by signature, so that we don't copy the same function many times (and to avoid name
        ///     conflicts).
        /// </summary>
        /// <seealso cref="GenerateStaticMethodCached" />
        private readonly HashSet<MethodSignature> cachedStaticMethods = new();

        public GraphCompilation(GraphCompiler.Settings settings = default)
        {
            Settings = settings;

            // The naming is critical in the following code, otherwise the assembly will fail to save, silently.
            // The Assembly/Module/FilePath must all match.
            string assemblyName = "LatticeGraphAssembly";

            CodeGenAssembly = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName(assemblyName),
                settings.AssemblyAccess ?? AssemblyBuilderAccess.RunAndCollect);
            CodeGenModule = CodeGenAssembly.DefineDynamicModule(assemblyName + ".dll");
            generatedFunctionNodes = CodeGenModule.DefineType("GeneratedFunctionIRNodes",
                TypeAttributes.Abstract | TypeAttributes.Sealed | TypeAttributes.Public | TypeAttributes.Class);
        }

        /// <summary>
        ///     Call this when you are done building the graph compilation. It will complete the IL generation for any nodes
        ///     so the generated methods can be resolved.
        /// </summary>
        public void FinishConstruction()
        {
            generatedFunctionNodes.CreateType();

            // Throw out port mappings. These won't stay invariant as the graph is optimized and are only used for construction.
            Graph.WipePortMappings();
        }

        public void AddToplevelGraph(LatticeGraph graphAsset)
        {
            if (TopLevelGraphs.Contains(graphAsset))
            {
                Debug.LogError($"(Lattice) ICE: Graph [{graphAsset.name}] was added to compilation twice.");
                return;
            }

            TopLevelGraphs.Add(graphAsset);

            // Inline the subgraph for the graph into our top-level graph.
            var graphBody = BuildGraphBody(graphAsset);

            var nodeMap = Graph.CopyIntoGraph(graphBody, graphAsset.HashGuid.ToString(), new GraphPath(graphAsset));

            // Add an implicit 'Entity' node to every LatticeGraph. This is our fundamental lattice primitive (the for node).
            // Connect the entity node to the sub-graph's entity input, if it has one.
            if (graphBody.ImplicitEntityNode != null)
            {
                string guid = $"{graphAsset.name}_{graphAsset.GetInstanceID()}";
                var entityNode = Graph.AddFreeNode(new EntityIRNode(new Qualifier(guid, graphAsset.name)),
                    $"ThisEntity_{guid}", $"ThisEntity_{guid}");

                nodeMap[graphBody.ImplicitEntityNode.Node].AddInput("value", entityNode);
                EntityNodes[graphAsset] = entityNode;
            }
        }

        public bool ContainsGraphBody(LatticeGraph graphAsset)
        {
            return GraphBodies.ContainsKey(graphAsset);
        }

        /// <summary>Retrieves or builds the IR graph for this lattice graph within the compilation.</summary>
        private IRGraph BuildGraphBody(LatticeGraph graphAsset)
        {
            using ProfilerMarker.AutoScope marker = new ProfilerMarker("Lattice Graph Compile").Auto();

            // Skip, if the graph is already added.
            if (GraphBodies.TryGetValue(graphAsset, out IRGraph graph))
            {
                return graph;
            }

            graph = new IRGraph();

            // Generate nodes first.
            foreach (LatticeNode node in graphAsset.LatticeNodes())
            {
                try
                {
                    graph.CreateMapping(node.ToRootPath());
                    node.CompileToIR(graph);
                }
                catch (Exception e)
                {
                    if (!node.DoNotLogErrors)
                    {
                        Debug.LogError(
                            $"Syntax Error at [{node}]: {e.Message}\n\n StackTrace:\n" + e.StackTrace + "\n\n",
                            graphAsset);
                    }

                    graph.ReplaceNodeWithMalformed(node.ToRootPath(), e);
                }

                // Ensure some default mappings. This makes it easier to write nodes without getting everything perfectly setup.
                // If this fails, it's an ICE. But swallow it anyway for better error messaging.
                try
                {
                    SetupDefaults(graph, node.ToRootPath());
                }
                catch (Exception e)
                {
                    Debug.LogException(e, graphAsset);
                }
            }

            // Connect edges.
            foreach (SerializableEdge edge in graphAsset.NonDanglingEdges())
            {
                // Normal edges within graphs:
                if (!edge.IsRefEdge())
                {
                    // Look up the output port projection node on the input.
                    if (!graph.GetOutputMap(((LatticeNode)edge.fromNode).ToRootPath())
                              .TryGetValue(edge.fromPortIdentifier, out IRNodeRef inputNode))
                    {
                        Debug.LogError(
                            $"ICE: No IRNode was mapped for output port [{edge.fromPortIdentifier}] on node [{edge.fromNode}].",
                            graphAsset);
                        continue;
                    }

                    // Attach that to the correct input port on the toNode.
                    if (!graph.GetInputMap(((LatticeNode)edge.toNode).ToRootPath()).TryGetValue(edge.toPortIdentifier,
                            out (IRNode node, string irPort)? portMap))
                    {
                        Debug.LogError(
                            $"ICE: No IRNode was mapped for input port [{edge.toPortIdentifier}] on node [{edge.toNode}].",
                            graphAsset);
                        continue;
                    }

                    if (portMap == null)
                    {
                        // Do nothing. The port goes nowhere, intentionally.
                        continue;
                    }

                    // Add the edge.
                    portMap.Value.node.AddInput(portMap.Value.irPort, inputNode.Node);
                }
                else
                {
                    // Stitch this node into the mutation pipeline.
                    Debug.LogError($"ICE: Ref edges are not currently supported. Edge: [{edge}]");
                }
            }

            if (Settings.Debug)
            {
                var ids = new Dictionary<string, IRNode>();
                foreach (IRNode node in graph.Nodes)
                {
                    if (ids.TryGetValue(node.Id, out IRNode n))
                    {
                        Debug.LogError($"ICE: Two IRNodes have the same Id. Node [{node}] and [{n}]. Id:[{node.Id}]");
                    }
                    ids.Add(node.Id, node);
                }

                foreach (IRNodeRef n in graph.Inputs)
                {
                    if (n.Node.Ports.Count != 1)
                    {
                        Debug.LogError(
                            $"ICE: Input node in graph does not have 1 port. [{n.Node}][{n.Node.Ports.Count}]");
                    }
                }
            }

            GraphBodies[graphAsset] = graph;
            return graph;
        }

        /// <summary>
        ///     Calculates several different properties of the node, propagating them upwards and downwards through the graph.
        ///     This step can be computed static at build-time, but doesn't have to be. We use the metadata generated here during
        ///     the execution pass.
        /// </summary>
        public Metadata CompileNode(IRNode node)
        {
            Assert.IsNotNull(node, "Can't compile null node.");

            if (MetadataDb.TryGetValue(node, out Metadata compileData))
            {
                return compileData;
            }

            Assert.IsFalse(AnalysisFinished); // Cannot propagate (compile) node metadata after analysis phase. 

            // PreviousNodes are special cased. They need to calculate backwards using cycle-aware analysis.
            // However, all other nodes should not need to do this.
            Metadata metadata;
            try
            {
                if (node is PreviousIRNode)
                {
                    metadata = CompileNodeCycleAware(node, new HashSet<IRNode>());
                }
                else 
                {
                    var inputs = new List<(string portId, Metadata metadata)>();
                    foreach (var (portId, port) in node.Ports)
                    {
                        foreach (IRNode input in port.Inputs)
                        {
                            inputs.Add((portId, CompileNode(input)));
                        }
                    }

                    metadata = CalculateMetadata(node, inputs);
                }
            }
            catch (Exception e)
            {
                Debug.LogWarning($"ICE: Node failed to compile. [{node}]", Graph.GetOwner(node)?.Last.Graph);
                Debug.LogException(e, Graph.GetOwner(node)?.Last.Graph);
                metadata = new Metadata(null, typeof(ITypeUnknown), LatticePhases.GetLatticeDefaultPhase(),
                    new NodeCompilationError(node, "ICE: Node failed to compile."));
            }

            MetadataDb[node] = metadata;

            if (Verbose)
            {
                Debug.Log("(Compile Node) " + node);
            }

            return metadata;
        }

        // does not write to cache, and follows previous edges, breaking on cycles
        private Metadata CompileNodeCycleAware(IRNode node, HashSet<IRNode> visited)
        {
            if (MetadataDb.TryGetValue(node, out Metadata compileData))
            {
                return compileData;
            }

            if (visited.Count == 0)
            {
                Assert.IsTrue(node is PreviousIRNode,
                    "Cycle-aware compilation should only be used for previous nodes.");
            }

            visited.Add(node);

            var inputs = new List<(string portId, Metadata metadata)>();
            foreach (var (portId, port) in node.Ports)
            {
                foreach (IRNode input in port.Inputs)
                {
                    if (visited.Contains(input))
                    {
                        // Don't recurse into visited nodes, as cycles cannot change metadata output.
                        inputs.Add((portId, null));
                        continue;
                    }

                    inputs.Add((portId, CompileNodeCycleAware(input, visited)));
                }
            }

            if (node is PreviousIRNode prev)
            {
                inputs.Add((PreviousIRNode.BackRefFakePort, CompileNodeCycleAware(prev.BackRef.Node, visited)));
            }

            Metadata metadata = CalculateMetadata(node, inputs);

            return metadata;
        }

        /// <summary>
        ///     Calculates metadata for the node, based on its inputs. This is the main "single step" for the analysis pass,
        ///     run once for each node.
        /// </summary>
        public Metadata CalculateMetadata(IRNode node, IEnumerable<(string portId, Metadata node)> inputs)
        {
            Assert.IsTrue(!node.ExecutionOnly, "Node doesn't support analysis.");
            
            if (node is MalformedIRNode mnode)
            {
                return new Metadata(null, typeof(MalformedException), LatticePhases.GetLatticeDefaultPhase(),
                    new NodeCompilationError(node, mnode.Reason));
            }

            if (node is EntityIRNode enode)
            {
                return new Metadata(
                    enode.QualifierId,
                    typeof(Entity),
                    LatticePhases.GetLatticeDefaultPhase()
                );
            }

            // For the rest of the nodes with inputs, merge the metadata from all the inputs.
            // Some nodes have additional special handling.

            // compile all children, propagate DependsOnTime from inputs.
            Type executePhase = LatticePhases.GetLatticeDefaultPhase();
            Qualifier? qualifier = null;

            List<(string, Type)> inputTypes = new();

            NodeCompilationError error = null;

            foreach (var (portId, inputMetadata) in inputs)
            {
                if (inputMetadata == null)
                {
                    // If metadata was null, we hit a cycle. Pass null to the type calculation to signify this, 
                    // rather than a missing type.
                    inputTypes.Add((portId, typeof(ITypeUnknown)));
                    continue;
                }

                // Propagate compilation errors from inputs.
                if (inputMetadata.CompilationError != null)
                {
                    error = inputMetadata.CompilationError;
                }

                // Propagate required qualifiers if inputs require entity.
                // (QualifierTransformIRNode is handled specially below)
                if (inputMetadata.Qualifier != null && node is not QualifierTransformIRNode)
                {
                    if (qualifier != null
                        && !qualifier.Equals(inputMetadata.Qualifier)
                       )
                    {
                        error = new NodeCompilationError(node,
                            $"Inputs with different entity qualifiers. Input qualifiers: [{inputMetadata.Qualifier}][{qualifier}]");
                        qualifier = null; // Null out the qualifier, because we'll just be returning an exception.
                    }
                    else
                    {
                        qualifier = inputMetadata.Qualifier;
                    }
                }

                // Propagate the latest-running execute phase.
                if (inputMetadata.ExecutionPhase != executePhase)
                {
                    TryMergePhase(node, ref executePhase, inputMetadata.ExecutionPhase, ref error);
                }

                inputTypes.Add((portId, inputMetadata.OutputType));
            }

            // Apply the system phase from this node.
            if (node.SystemPhase != null)
            {
                TryMergePhase(node, ref executePhase, node.SystemPhase, ref error);
            }

            // The Qualifier transform node takes the qualifier from the qualifier input.
            if (node is QualifierTransformIRNode)
            {
                foreach (var (portId, inputMetadata) in inputs)
                {
                    if (portId == QualifierTransformIRNode.PortQualifier)
                    {
                        qualifier = inputMetadata.Qualifier;
                    }
                }
            }

            // Calculate inferred output types, if node requires it.
            // Type inference does not work on cyclical links. 
            Type outputType = node.CalculateType(inputTypes);

            Assert.IsNotNull(outputType); // Should at least always return ITypeUnknown.

            return new Metadata
            (
                qualifier,
                outputType,
                executePhase,
                error
            );
        }

        private void TryMergePhase(IRNode node, ref Type existingPhase, Type inputPhase, ref NodeCompilationError error)
        {
            if (existingPhase == inputPhase)
            {
                // Phases are the same, do nothing.
                return;
            }

            // Find the last shared parent, and sort those systems.
            List<Type> existingGroups = LatticeUtils.GetSystemGroupChain(existingPhase);
            List<Type> inputGroups = LatticeUtils.GetSystemGroupChain(inputPhase);

            for (int i = 0; i < existingGroups.Count; i++)
            {
                Type inputGroup = inputGroups[i];
                Type existingGroup = existingGroups[i];
                if (existingGroup == inputGroup)
                {
                    continue;
                }

                // Found first differing system. Sort these under the other.
                bool? orderedAfter = LatticeUtils.SystemOrderedAfter(inputGroup, existingGroup);

                if (!orderedAfter.HasValue)
                {
                    error = new NodeCompilationError(node,
                        "Cannot compile: Lattice Phases for input nodes were not fully ordered (UpdateAfter/UpdateBefore). Info:\n" +
                        $"Phases not fully ordered: [{inputPhase}] and [{existingPhase}]\n" +
                        $"Because: missing system UpdateAfter/UpdateBefore between systems: [{inputGroup}] and [{existingGroup}]");
                    if (!node.DoNotLogErrors)
                    {
                        Debug.LogException(error);
                        CannotBeExecuted = true;
                    }
                    return;
                }

                existingPhase = orderedAfter.Value ? inputPhase : existingPhase;
                return;
            }
        }

        /// <summary>Reduce qualifiers if the node does not require them.</summary>
        public Entity ReduceQualifiers(IRNode node, Entity qualifiers)
        {
            return CompileNode(node).Qualifier == null ? Entity.Null : qualifiers;
        }

        /// <summary>
        ///     Allows you to generate a static method with IL. Build the body of the method in the called lambda. All
        ///     generated functions are cached by type signature, to avoid duplication. All methods are generated underneath a
        ///     shared Type.
        /// </summary>
        /// <remarks>
        ///     This is very useful when you would like a LatticeNode that does something with reflection but don't want to
        ///     pay the high cost. For example, a node that reads from a specific field of a struct.
        /// </remarks>
        /// <param name="methodName">The name of the new method.</param>
        /// <param name="returnType">The return type of the method.</param>
        /// <param name="parameters">Parameter names and types.</param>
        /// <param name="genericTypeArguments">
        ///     This is a fake parameter. It doesn't add type parameters to the function, but it is
        ///     used for deduplication. This helps catch bugs when we only differentiate functions by name, and preps for later
        ///     supporting real generics.
        /// </param>
        /// <param name="methodGeneration">The body of IL for the function. See SharpLab.io for more help.</param>
        public MethodSignature GenerateStaticMethodCached(string methodName, Type returnType,
                                                          (Type type, string name)[] parameters,
                                                          Type[] genericTypeArguments,
                                                          Action<GroboIL> methodGeneration
        )
        {
            Assert.IsFalse(Graph.IsSealed, "The graph cannot be modified after construction.");

            MethodSignature signature = new()
            {
                Name = methodName,
                Parameters = parameters,
                ReturnType = returnType,
                DeclaringType = generatedFunctionNodes,
                GenericTypeArguments = genericTypeArguments ?? new Type[] { }
            };

            // Return the method if it's already been generated.
            if (cachedStaticMethods.Contains(signature))
            {
                return signature;
            }

            MethodBuilder method = generatedFunctionNodes.DefineMethod(methodName,
                MethodAttributes.Public | MethodAttributes.Static, returnType,
                parameters.Select(p => p.type).ToArray());

            GroboIL emit = new(method);

            // We have the user return a methodBuilder to make sure finish the method and set parameter names.
            methodGeneration(emit);

            for (int i = 0; i < parameters.Length; i++)
            {
                (Type type, string name) param = parameters[i];
                method.DefineParameter(i + 1, ParameterAttributes.None, param.name); // param 0 is the return type!
            }

            cachedStaticMethods.Add(signature);

            return signature;
        }

        public void DeduplicatedCodeGen<Key, NodeType>(string typeName, Func<NodeType, Key> keyFunction,
                                                       Func<NodeType, TypeBuilder, MethodBuilder> codegen)
            where NodeType : FunctionIRNode
        {
            TypeBuilder b = CodeGenModule.DefineType(typeName,
                TypeAttributes.Public | TypeAttributes.Class | TypeAttributes.Sealed);

            Dictionary<Key, MethodBuilder> methods = new();
            foreach (var n in Graph.Nodes)
            {
                if (n is NodeType node)
                {
                    Key key = keyFunction(node);

                    // This method is already generated, use the cached version.
                    if (!methods.TryGetValue(key, out _))
                    {
                        methods[key] = codegen(node, b);
                    }
                }
            }

            Type t = b.CreateType();

            // Close the type and resolve the method handles.
            foreach (var n in Graph.Nodes)
            {
                if (n is NodeType node)
                {
                    Key key = keyFunction(node);
                    string name = methods[key].Name;
                    try
                    {
                        node.SetMethod(t.GetMethod(name));
                    }
                    catch (AmbiguousMatchException e)
                    {
                        Debug.LogError($"Generated function was duplicated [{t.Name}.{name}]");
                        throw;
                    }
                }
            }
        }

        /// <summary>
        ///     Returns the set of nodes that are referenced by another work unit. These values will need to be stored in our
        ///     cross-unit data storage.
        /// </summary>
        public HashSet<IRNode> GetReferencedByAnotherWorkUnit()
        {
            if (referencedByAnotherWorkUnit == null)
            {
                Assert.IsTrue(Graph.IsSealed);

                referencedByAnotherWorkUnit = new HashSet<IRNode>();
                foreach (var node in Graph.Nodes)
                {
                    foreach (var (_, usage) in node.Usages)
                    {
                        if (WorkUnitForNode[usage] != WorkUnitForNode[node])
                        {
                            referencedByAnotherWorkUnit.Add(node);
                            break;
                        }
                    }
                }
            }

            return referencedByAnotherWorkUnit;
        }

        public HashSet<Qualifier> GetQualifiers()
        {
            if (allQualifiers == null)
            {
                allQualifiers = new HashSet<Qualifier>();
                foreach (var n in Graph.Nodes)
                {
                    Qualifier? qualifier = CompileNode(n).Qualifier;
                    if (qualifier.HasValue)
                    {
                        allQualifiers.Add(qualifier.Value);
                    }
                }
            }

            return allQualifiers;
        }

        private ProfilerMarker profilerGenerateIL = new("Generate Lattice IL");
        private ProfilerMarker profilerGenerateILWorkUnit = new("Generate WorkUnit IL");
        private ProfilerMarker profilerCreateDelegate = new("Create WorkUnit Delegate");

        // This is the second stage of compilation. Generating work units.
        internal void GenerateWorkUnits()
        {
            // Generate work units. We do this before code generation because it's not necessary for editor feedback.
            WorkUnitPartitioning.PartitionGraphIntoWorkUnits(this);
        }

        public void GenerateIL()
        {
            GenerateWorkUnits();

            // Note: It should be possible to generate these execution methods *within* the GraphCompilations assembly.
            // However, this causes MethodAccessExceptions when calling into private static methods of other classes. 
            // (ie. with FunctionIRNodes). There seem to be ways to get around this. Notably:
            // - IgnoreAccessChecksToAttribute -- Apparently observed by the runtime but not documented.
            // - SecurityPermissionAttribute -- Deprecated, but supposedly could work.
            // I tried the latter, and it didn't help, so I figure we can come back to that if we want to keep all the 
            // generated code in a single assembly.

            // Generate IL for each work unit:
            var workUnitMethods = new Dictionary<WorkUnit, DynamicMethod>();
            int nodeCount = 0;
            StringBuilder workUnits = new();
            Stopwatch timer = Stopwatch.StartNew();
            using (profilerGenerateIL.Auto())
            {
                foreach (WorkUnit workUnit in WorkUnitsTopological)
                {
                    using (profilerGenerateILWorkUnit.Auto())
                    {
                        DynamicMethod method = new DynamicMethod("ExecuteLatticeWorkUnit_" + workUnit.Name,
                            typeof(void),
                            new[] { typeof(IRExecution), typeof(EntityManager) });
                        GroboIL emit = new GroboIL(method);

                        bool success = ILGeneration.EmitNodeExecutionIL(emit, this, workUnit.Nodes);
                        if (success)
                        {
                            workUnitMethods[workUnit] = method;

                            workUnits.Append(workUnit.Name);
                            workUnits.Append(" -- ");
                            workUnits.Append(workUnit.Nodes.Count);
                            workUnits.Append(" nodes");
                            workUnits.AppendLine(" nodes");
                            nodeCount += workUnit.Nodes.Count;
                        }
                        else
                        {
                            Debug.LogError(
                                $"(Lattice) IL Generation failed for Lattice work unit [{workUnit.Name}]. ({timer.ElapsedMilliseconds}ms)");
                            CannotBeExecuted = true;
                        }
                    }
                }

                // Build delegates for each method.
                WorkUnitDelegates = new Dictionary<WorkUnit, ILGeneration.ExecuteGraph>();

                foreach (var (workUnit, emit) in workUnitMethods)
                {
                    try
                    {
                        using (profilerCreateDelegate.Auto())
                        {
                            // Get the method that executes the work unit and convert to a delegate for speed.
                            ILGeneration.ExecuteGraph workDelegate =
                                (ILGeneration.ExecuteGraph)emit.CreateDelegate(typeof(ILGeneration.ExecuteGraph));

                            WorkUnitDelegates[workUnit] = workDelegate;
                        }
                    }
                    catch (Exception e)
                    {
                        Debug.LogError($"(Lattice) IL validation failed for Lattice WorkUnit [{workUnit.Name}]:");
                        Debug.LogException(e);
                        CannotBeExecuted = true;
                        return;
                    }
                }
            }
            timer.Stop();

            Debug.Log(
                $"(Lattice) Generated IL for Lattice Graph. Work Units: [{WorkUnitsTopological.Count}] [{nodeCount} nodes] ({timer.ElapsedMilliseconds}ms)\n{workUnits}");
        }

        [CanBeNull] // If there's no nodes in the phase.
        public List<WorkUnit> GetWorkUnitsForPhase(Type phase)
        {
            Assert.IsTrue(Graph.IsSealed);

            if (WorkUnitsInPhase == null)
            {
                GenerateIL();
            }

            return WorkUnitsInPhase!.ContainsKey(phase) ? WorkUnitsInPhase[phase] : null;
        }

        public ILGeneration.ExecuteGraph GetDelegateForWorkUnit(WorkUnit unit)
        {
            return WorkUnitDelegates[unit];
        }

        private static bool IsNullable(Type t)
        {
            return t.IsGenericType && t.GetGenericTypeDefinition() == typeof(Nullable<>);
        }

        /// <summary>Gets all dependencies of a node. May be somewhat slow.</summary>
        public HashSet<IRNode> GetAllDependencies(IRNode node)
        {
            HashSet<IRNode> output = new();
            GetAllDependencies(node, output);
            return output;
        }

        /// <summary>Gets all dependencies of a node. May be somewhat slow.</summary>
        private void GetAllDependencies(IRNode node, HashSet<IRNode> output)
        {
            if (output.Contains(node))
            {
                // Return to avoid going down the same route multiple times.
                return;
            }

            output.Add(node);

            foreach (var input in node.InputNodes())
            {
                GetAllDependencies(input, output);
            }
        }

        public Qualifier? GetQualifier(LatticeGraph graph)
        {
            if (EntityNodes.TryGetValue(graph, out var node))
            {
                return node.QualifierId;
            }

            return null;
        }

        /// <summary>
        ///     Makes sure nodes have an output port mapping and some other default mappings. For single output port nodes,
        ///     just maps them to the added node.
        /// </summary>
        private static void SetupDefaults(IRGraph compilation, CodePath span)
        {
            // Add primary node marker if there's only one ir node.
            if (compilation.GetPrimaryNode(span) == null)
            {
                var nodes = compilation.GetNodesUnderPath(span);
                if (nodes.Count > 1)
                {
                    Debug.LogError($"No primary node specified for node [{span}].");
                }
                else if (nodes.Count == 1)
                {
                    compilation.SetPrimaryNode(span, nodes[0]);
                }
                else
                {
                    Debug.LogError($"No nodes created for node [{span}].");
                }
            }

            // (Doesn't overwrite manually specified output mapping.)

            // If the user didn't specify an output port map, attempt to generate it.
            var outputMap = compilation.GetOutputMap(span);
            if (!outputMap.Any())
            {
                // Add default mapping for single output port nodes.
                if (span.Last.GetValueOutputs().Count() == 1)
                {
                    var nodes = compilation.GetNodesUnderPath(span);
                    if (nodes.Count != 1)
                    {
                        Debug.LogError(
                            $"Couldn't add default output port mapping to node [{span}]. Node count: {nodes.Count}.");
                        return;
                    }

                    compilation.MapOutputPort(span, span.Last.OutputPorts[0].portData.identifier, nodes[0]);
                }
                else if (span.Last.GetValueOutputs().Count() > 1)
                {
                    Debug.LogError($"No output port mapping found for compiled node [{span}].");
                }
            }
            else
            {
                // If the node specified an output port mapping, verify it.
                foreach (NodePort output in span.Last.GetValueOutputs())
                {
                    if (!outputMap.ContainsKey(output.portData.identifier))
                    {
                        Debug.LogError(
                            $"Incomplete OutputPortMap for compiled node [{span}]. Missing port [{output.portData.identifier}]");
                    }
                }
            }

            var inputMap = compilation.GetInputMap(span);
            if (inputMap.Any())
            {
                // If the node specified an input port mapping, verify it.
                foreach (NodePort input in span.Last.GetLogicalInputs())
                {
                    if (!inputMap.ContainsKey(input.portData.identifier))
                    {
                        Debug.LogError(
                            $"Incomplete InputPortMap for compiled node [{span}]. Missing port [{input.portData.identifier}]");
                    }
                }
            }
            else
            {
                // If no input port map is provided, and there's only a single node, map inputs there.
                var nodes = compilation.GetNodesUnderPath(span);
                if (nodes.Count == 1)
                {
                    if (nodes[0] is MalformedIRNode)
                    {
                        // Map all input ports nowhere. 
                        // Todo: Eventually we will want to insert fake input nodes so that we can access
                        // the type information for the editor. 
                        foreach (NodePort port in span.Last.GetLogicalInputs())
                        {
                            compilation.MapInputPort(span, port.portData.identifier, null);
                        }
                    }
                    else
                    {
                        compilation.MapInputPorts(span, nodes[0]);
                    }
                }
                else if (span.Last.GetLogicalInputs().Any())
                {
                    Debug.LogError($"No input port mapping found for compiled node [{span}].");
                }
            }
        }

        /// <summary>
        ///     Returns a debug string in GraphViz syntax, representing the entire graph.  Can be opened with online GraphViz
        ///     viewers. See the button on the Lattice Toolbar.
        /// </summary>
        public static string ToDot(GraphCompilation compilation, List<IRNode> nodes = null)
        {
            const bool showPhase = false; // Label nodes with phase
            const bool showExternalRefs = true; // Label nodes with number of external refs (ie. primary node)
            const bool showQualifier = true; // Label nodes with qualifier
            const bool showType = true; // Label nodes with output type
            const bool showNodeType = true; // Label nodes with IR node type
            const bool showWorkUnit = false; // Label nodes with work unit
            const bool showError = true; // Label nodes with errors, if they have any.
            const bool colorByThrow = false; // Color green if the node *can't* throw.
            const bool colorByMainThread = false; // Color gray if the node runs on the main thread.
            const bool colorByPure = true; // Color gray if the node is pure code
            const bool colorByWorkUnit = false; // Color a random color matching the work unit.

            nodes ??= compilation.Graph.Nodes;

            if (showWorkUnit || colorByWorkUnit)
            {
                compilation.GenerateIL(); // Need to have IL generated to have the work units.
            }

            StringBuilder dot = new();
            dot.AppendLine("digraph G {");
            dot.AppendLine("\trankdir = BT");

            // Add nodes to the .dot file.
            Dictionary<WorkUnit, string> workUnitColors = new();
            IEnumerator<string> colorGenerator = LatticeUtils.GenerateInfiniteDotColors().GetEnumerator();
            foreach (IRNode irNode in nodes)
            {
                string nodeId = irNode.Id;
                Metadata compileData = compilation.CompileNode(irNode);
                string nodeLabel = $"{irNode.DebugName}\n{irNode.DebugPath}";

                if (showExternalRefs)
                {
                    nodeLabel += $"({compilation.Graph.CountExternalReferences(irNode)})";
                }

                if (showNodeType)
                {
                    nodeLabel += $"\n({irNode.GetType().Name})";
                }

                if (showType)
                {
                    nodeLabel += $"\n{GraphUtils.GetReadableTypeName(compileData.OutputType)}";
                }

                if (showQualifier)
                {
                    nodeLabel += $"\n{compileData.Qualifier}";
                }

                if (showPhase)
                {
                    nodeLabel += $"\n{compileData.ExecutionPhase}";
                }

                if (showWorkUnit)
                {
                    nodeLabel += $"\n{compilation.WorkUnitForNode[irNode].Name}";
                }

                if (showError)
                {
                    if (compileData.CompilationError != null)
                    {
                        nodeLabel += $"\nError: [{compileData.CompilationError.Message}]";
                    }
                }

                string nodeColor = "";
                if (colorByThrow)
                {
                    nodeColor = irNode.CheckExceptions ? ",color=\"darkseagreen3\",style=filled" : "";
                }

                if (colorByPure)
                {
                    nodeColor = irNode.Pure ? ",color=\"gray\",style=filled" : "";
                }

                if (colorByMainThread)
                {
                    nodeColor = irNode.MustRunOnMainThread ? ",color=\"gray\",style=filled" : "";
                }

                if (colorByWorkUnit)
                {
                    WorkUnit wunit = compilation.WorkUnitForNode[irNode];
                    if (!workUnitColors.TryGetValue(wunit, out string color))
                    {
                        colorGenerator.MoveNext();
                        color = colorGenerator.Current;
                        workUnitColors[wunit] = color;
                    }
                    nodeColor = $",color=\"{color}\",style=filled";
                }

                dot.AppendLine($"\t\"{nodeId}\" [label=\"{nodeLabel}\"{nodeColor}];");
            }

            // Add edges to the .dot file.
            foreach (IRNode irNode in nodes)
            {
                string sourceId = irNode.Id;
                foreach (var (portId, port) in irNode.Ports)
                {
                    foreach (IRNode inputNode in port.Inputs)
                    {
                        string targetId = inputNode.Id;
                        dot.AppendLine($"\t\"{sourceId}\" -> \"{targetId}\" [label=\"{portId}\"];");
                    }
                }

                if (irNode is PreviousIRNode pNode)
                {
                    string targetId = pNode.BackRef.Node.Id;
                    dot.AppendLine(
                        $"\t\"{sourceId}\" -> \"{targetId}\" [label=\"backref\" color=blue constraint=false];");
                }
            }

            dot.AppendLine("}");
            return dot.ToString();
        }
    }

    /// <summary>The node has some static error due to misconfiguration of the graph. The node cannot be executed.</summary>
    public class NodeCompilationError : Exception
    {
        public IRNode Node;

        public NodeCompilationError(IRNode node, string message, Exception e) : base(message, e)
        {
            Node = node;
        }

        public NodeCompilationError(IRNode node, Exception e) : this(node, null, e) { }

        public NodeCompilationError(IRNode node, string message) : this(node, null, new Exception(message)) { }

        public override string ToString()
        {
            if (InnerException is MalformedException e)
            {
                string err = $"{e.Message} [{Node}]";
                if (e.InnerException != null)
                {
                    err += $"\n{e.InnerException}";
                }
                return err;
            }

            return $"Node [{Node}] had compile error. {Message}\n{InnerException}";
        }
    }

    public enum ProfileMarkerGranularity
    {
        IrNode, // Measures each IRNode separately.
        Node, // Measures each LatticeNode separately.
        Graph, // Measures each Graph separately.
        None
    }
}
