// Disable line wrapping so we can comment the IR more easily.
// @formatter:wrap_lines false

using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using GrEmit;
using JetBrains.Annotations;
using Lattice.Nodes;
using Lattice.Utils;
using Unity.Assertions;
using Unity.Collections;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Entities;
using Unity.Profiling;
using UnityEngine;
using Local = GrEmit.GroboIL.Local;
using Label = GrEmit.GroboIL.Label;

// Performance improvements:
//  - Move DoNotLogErrors check to compile-time.
//  - Can we emit more efficient code for the big function calls at the end of a node's execution? 

namespace Lattice.IR
{
    /// <summary>Generates .NET IL to execute IR node graphs. This is the primary executor for Lattice Graphs.</summary>
    public static class ILGeneration
    {
        public delegate void ExecuteGraph(IRExecution execution, EntityManager entityManager);

        [MustUseReturnValue] // If the IR generation fails, the IL / method body is left in an indeterminate state.
        public static bool EmitNodeExecutionIL(GroboIL emit, GraphCompilation compilation, HashSet<IRNode> subset)
        {
            const ushort argumentExecutionIdx = 0;
            const ushort argumentEntityManagerIdx = 1;

            try
            {
                // Emits code that loads the value calculated by the given node onto the stack.
                // We pass the consumer node as well, so we can generate better error messages if this load fails.
                var executionEmitted = new HashSet<IRNode>();

                // A UnsafeList<Entity> for each qualifier. Used to get the list of entities for a lattice.
                Dictionary<Qualifier, Local> entitiesByQualifier = new();

                // Locals for the output values of each node. Each local will be either a plain T or List<T> (if the node is in a lattice).
                Dictionary<IRNode, Local> outputLocals = new();

                // Locals for any exception generated by the node. Each local will be either a plain Exception or List<Exception> (if the node is in a lattice).
                Dictionary<IRNode, Local> outputExceptions = new();

                // Shared functions for emitting code:

                // Emits a Local that is either type T or List<T>, depending on if we're in a lattice.
                Local EmitDeclareLatticedLocal(IRNode node, Type type, string name, int pool)
                {
                    Metadata compileData = compilation.CompileNode(node);

                    Local local;
                    if (compileData.Qualifier.HasValue)
                    {
                        local = emit.DeclareLocal(typeof(List<>).MakeGenericType(type), name);

                        // Get the cached exception value list, and store it into the local.
                        emit.Ldarg(argumentExecutionIdx); // Load the IRExecution as argument 1.
                        emit.Ldc_I4(compilation.Graph.NodeIndices[node]); // Load the node idx as argument 2.
                        emit.Ldc_I4(pool); // Which pool to pull from? Argument 3.
                        emit.Call(typeof(ILGeneration).GetMethod(nameof(GetCachedLatticedList))!.MakeGenericMethod(type));
                        emit.Stloc(local);
                    }
                    else
                    {
                        local = emit.DeclareLocal(type, name);
                    }

                    return local;
                }

                // - Expects a value to be on the top of the stack.
                // Stores the value as the output value of the given node, putting it into the raw local or into the list values.
                void EmitStoreIntoLatticedLocal(IRNode node, Local local, Local idx)
                {
                    Metadata compileData = compilation.CompileNode(node);
                    if (compileData.Qualifier.HasValue)
                    {
                        Assert.IsTrue(local.Type.GetGenericTypeDefinition() == typeof(List<>));
                        Local tmp = emit.DeclareLocal(local.Type.GenericTypeArguments[0], "tmp");
                        emit.Stloc(tmp); // Store the value temporarily on the stack.

                        // Set the value into the list, under the entityIndex.
                        emit.Ldloc(local); // Load the List<T> as argument 1.
                        emit.Ldloc(idx); // Load the idx in the lattice as arg 2.
                        emit.Ldloc(tmp); // Load the output value as an argument 3.
                        emit.Call(local.Type.GetMethod("set_Item", BindingFlags.Public | BindingFlags.Instance)!);
                    }
                    else
                    {
                        emit.Stloc(local);
                    }
                }

                // - Loads a value onto the stack: the value of the latticed local at this idx.
                // Stores the value as the output value of the given node, putting it into the local or into the list of output values.
                void EmitLoadLatticedLocal(IRNode node, Local local, [CanBeNull] Local idx)
                {
                    Metadata compileData = compilation.CompileNode(node);
                    if (compileData.Qualifier.HasValue)
                    {
                        Assert.IsTrue(local.Type.GetGenericTypeDefinition() == typeof(List<>));
                        Assert.IsNotNull(idx);

                        emit.Ldloc(local); // Push the list onto the stack.
                        emit.Ldloc(idx); // Push the idx to load from onto the stack.
                        emit.Call(local.Type.GetMethod("get_Item", BindingFlags.Public | BindingFlags.Instance)!);

                        // The value from the latticed local is now on the stack.
                    }
                    else
                    {
                        emit.Ldloc(local); // Just load the standard local, non-latticed.
                    }
                }

                // Loads the entire lattice for the given node into local.
                void EmitReadCrossPhaseLocal(IRNode node, Local outputLocal, int pool)
                {
                    emit.Ldarg(argumentExecutionIdx); // Load the IRExecution as arg1
                    emit.Ldc_I4(compilation.Graph.NodeIndices[node]); // Load the node index as arg2
                    emit.Ldc_I4(pool); // Load 0 or 1 (output or exception) as arg3.
                    emit.Call(typeof(ILGeneration).GetMethod(nameof(LoadCrossPhaseLocal)));

                    // Unboxes the value to the correct local type, if it's a value type. Casts, if it's a reference.
                    if (outputLocal.Type.IsValueType)
                    {
                        emit.Unbox(outputLocal.Type);
                        emit.Ldobj(outputLocal.Type);
                    }
                    else
                    {
                        emit.Castclass(outputLocal.Type);
                    }

                    // Store into local.
                    emit.Stloc(outputLocal);
                }

                // Stores the given local into the cross phase storage.
                void EmitStoreCrossPhaseLocal(IRNode node, Local outputLocal, int pool)
                {
                    emit.Ldarg(argumentExecutionIdx); // Load the IRExecution as arg1
                    emit.Ldc_I4(compilation.Graph.NodeIndices[node]); // Load the node index as arg2
                    emit.Ldc_I4(pool); // Load 0 or 1 (output or exception) as arg3.

                    emit.Ldloc(outputLocal);

                    // If the local is a plain value type we'll need to box it up first.
                    if (outputLocal.Type.IsValueType)
                    {
                        emit.Box(outputLocal.Type);
                    }

                    emit.Call(typeof(ILGeneration).GetMethod(nameof(StoreCrossPhaseLocal)));
                }

                // Stores the value for the given node in the output local, or, if the value is an exception, stores it
                // in the output exception local and jumps away.
                void EmitReadNodeValue(IRNode node, [CanBeNull] Local entityIdx, Local outNodeValue, Local outExceptionValue, Label jumpOnException)
                {
                    if (!executionEmitted.Contains(node) && subset.Contains(node))
                    {
                        throw new Exception($"ICE: Tried to emit load for node, but its execution hasn't been emitted yet. [{node}]");
                    }

                    // Load and check if the input value is an exception. If so, store it into the exception local and jump to end of node execution.
                    emit.Ldarg(argumentExecutionIdx); // Load IRExecution as arg1
                    emit.Ldc_I4(compilation.Graph.NodeIndices[node]); // Load the node index as arg2
                    EmitLoadLatticedLocal(node, outputExceptions[node], entityIdx); // Load the input exception value, may be null, as arg3
                    emit.Ldloca(outExceptionValue); // Load a 'ref' to the exception local of this node, arg4.
                    emit.Call(typeof(ILGeneration).GetMethod(nameof(CheckInputException))); // Meat of function happens here.

                    // If there was an exception, jump to the end of execution.
                    emit.Brtrue(jumpOnException);

                    // If the input value is not an exception, continue and load the input value into the given output local.
                    EmitLoadLatticedLocal(node, outputLocals[node], entityIdx);
                    emit.Stloc(outNodeValue);
                }

                // Calculate the nodes that are outside the phase, but still inputs. These will be loaded from 
                // cross-phase storage.
                HashSet<IRNode> phaseInputs = new();
                foreach (var node in subset)
                {
                    foreach (var input in node.InputNodes())
                    {
                        if (!subset.Contains(input))
                        {
                            phaseInputs.Add(input);
                        }
                    }
                }

                // 
                // ===============================================================
                // ======================= Begin Emit IL =========================
                // ===============================================================
                // 

                // Emit local variables holding the entity lists for each qualifier.
                foreach (var qualifier in compilation.GetQualifiers())
                {
                    // Emit local for the entity list. 
                    var entityListLocal = emit.DeclareLocal(typeof(UnsafeList<Entity>), qualifier.ShortName());

                    // Load data from execution into list.
                    emit.Ldarg(argumentExecutionIdx);
                    emit.Ldstr(qualifier.guid);
                    emit.Call(typeof(ILGeneration).GetMethod(nameof(LoadEntityList)));

                    // Store it to the local variable.
                    emit.Stloc(entityListLocal);

                    entitiesByQualifier[qualifier] = entityListLocal;
                }

                // Begin emitting IL for each node. We execute each node in topological order.
                // For nodes that are executed for several entities, we run all executions together in a loop. 
                // Outputs of execution for each node are stored and loaded from IRExecution.
                Local latticeEntity = emit.DeclareLocal(typeof(Entity), "latticeEntity");
                Local latticeIdx = emit.DeclareLocal(typeof(int), "latticeIdx");

                List<IRNode> topoSort = compilation.Graph.GetTopologicalSort();
                foreach (IRNode node in topoSort)
                {
                    try
                    {
                        // If this node isn't part of the phase, but is a phase input, load its output buffers.
                        if (phaseInputs.Contains(node))
                        {
                            Assert.IsFalse(subset.Contains(node));

                            Metadata compile = compilation.CompileNode(node);
                            outputLocals[node] = EmitDeclareLatticedLocal(node, compile.OutputType, node.DebugName, 0);
                            outputExceptions[node] = EmitDeclareLatticedLocal(node, typeof(Exception), node.DebugName, 1);

                            // Load from the cross-phase store into the local.
                            EmitReadCrossPhaseLocal(node, outputLocals[node], 0);
                            EmitReadCrossPhaseLocal(node, outputExceptions[node], 1);

                            continue;
                        }

                        // Only emit execution for nodes in the specified subset of the graph. This is used for phases.
                        // This is safe, because all node executions will throw if their inputs have not been executed yet.
                        if (!subset.Contains(node))
                        {
                            continue;
                        }

                        Assert.IsFalse(node.CannotExecute, "Abstract IR node was not removed before code generation.");

                        Metadata compileData = compilation.CompileNode(node);
                        int nodeIdx = compilation.Graph.NodeIndices[node];

                        // After executing, all IRNodes leave a single value on the stack. Store it into a temp local.
                        // The local has the output type of the Irnode.
                        Type executionOutputType = compileData.OutputType;

                        // Emit profile marker begin.
                        if (compilation.ProfileMarkerOptions != ProfileMarkerGranularity.None)
                        {
                            // Load the profiler marker for this node execution.
                            emit.Ldarg(argumentExecutionIdx);
                            emit.Ldfld(typeof(IRExecution).GetField(nameof(IRExecution.ProfilerMarkers)));
                            emit.Ldc_I4(nodeIdx);
                            emit.Ldelema(typeof(ProfilerMarker));

                            // Call the Begin method.
                            emit.Call(typeof(ProfilerMarker).GetMethod(nameof(ProfilerMarker.Begin), Type.EmptyTypes));
                        }

                        // Setup the local variables to store output and exceptions from this node.
                        Local latticedOutputs = EmitDeclareLatticedLocal(node, executionOutputType, node.DebugName, 0);
                        outputLocals[node] = latticedOutputs;

                        Local latticedExceptions = EmitDeclareLatticedLocal(node, typeof(Exception), node.DebugName, 1);
                        outputExceptions[node] = latticedExceptions;

                        Label latticeLoopStart = null; // Null if this node is not within a lattice.
                        Label latticeLoopEnd = null; // Null if this node is not within a lattice.

                        // Emit looping for nodes that are within a lattice:
                        // =================================================
                        if (compileData.Qualifier.HasValue)
                        {
                            // Emit loop if we're within a lattice. Store entity as entity local variable.

                            latticeLoopStart = emit.DefineLabel("lattice_loop_begin_" + nodeIdx);
                            latticeLoopEnd = emit.DefineLabel("lattice_loop_end_" + nodeIdx);

                            // Set latticeIdx local variable to 0.
                            emit.Ldc_I4(0);
                            emit.Stloc(latticeIdx);

                            // Set up a loop marker. We'll jump back to this as we iterate through the lattice.
                            emit.MarkLabel(latticeLoopStart);

                            // Iterate entities array for this node. Returns false if there are no more entities in this lattice.
                            // Calls EnumerateLattice:
                            emit.Ldloc(entitiesByQualifier[compileData.Qualifier.Value]);
                            emit.Ldloc(latticeIdx); // Load the lattice index var as a ref for arg2. It's incremented.
                            emit.Ldloca(latticeEntity); // Load the lattice entity variable as a ref for arg3
                            emit.Call(typeof(ILGeneration).GetMethod(nameof(EnumerateLattice)));

                            // Returns true if we have another entity to execute, false if not. 
                            emit.Brfalse(latticeLoopEnd);
                        }
                        else
                        {
                            // If we're not in a lattice, clear the local variables for the entity and index.
                            emit.Ldloca(latticeEntity);
                            emit.Initobj(typeof(Entity));

                            emit.Ldc_I4(0);
                            emit.Stloc(latticeIdx);
                        }

                        // Create local variables inside the loop for the output and exception values.
                        Local outputValue = emit.DeclareLocal(executionOutputType, "outputValue");
                        Local exceptionValue = emit.DeclareLocal(typeof(Exception), "exception");

                        // Emit exception handling. 
                        //  - If the execution of this node throws, catch it and return the exception.
                        //  - If any inputs return exceptions, skip this node and return an exception. (handled via throw)
                        // ===============================================================================================
                        if (node.CheckExceptions)
                        {
                            emit.BeginExceptionBlock(); // Roughly.. "try {"
                        }

                        // Emit the execution code for each node type:
                        // ===========================================

                        // Jump to this label if you want to skip the execution of the function.
                        // This expects a valid return value for the node to be on the stack, and it will be stored into the output for this node.
                        Label skipFunctionExecution = emit.DefineLabel("skipFunctionExecution");

                        // If the node failed to compile earlier, load the compilation exception onto the stack.
                        // That's all we have to execute for this node.
                        if (compileData.CompilationError != null)
                        {
                            // Load the exception onto the stack. 
                            emit.Ldarg(argumentExecutionIdx); // Load the ExecutionContext as arg0
                            emit.Ldc_I4(nodeIdx); // Load the node index as arg1
                            emit.Call(typeof(ILGeneration).GetMethod(nameof(LoadCompilationError)));
                            emit.Stloc(exceptionValue); // Store the error in the exception local.

                            // We're done, continue on to the end node finish
                        }
                        else
                        {
                            switch (node)
                            {
                                case FunctionIRNode fNode:
                                {
                                    // A list of local variables, one for each input parameter to the function. In order of the calling function.
                                    // Inputs are loaded here first, and then later stuffed into the execution.
                                    List<Local> parmeterLocals = new();

                                    // Load the value for each input onto the stack.
                                    foreach (ParameterInfo param in fNode.Method.GetParameters())
                                    {
                                        if (param.IsIn)
                                        {
                                            throw new Exception(
                                                $"'in' parameters are not supported by compilation. [{fNode.Method}]");
                                        }

                                        if (param.IsOut)
                                        {
                                            throw new Exception(
                                                $"'out' parameters are not supported by compilation. [{fNode.Method}]");
                                        }

                                        string portName = param.Name;

                                        // A local for storing the loaded input parameter value for the function.
                                        Local paramLocal = emit.DeclareLocal(param.ParameterType, param.Name);

                                        // Parameters of type LatticeNode are passed implicitly as the parent of the IRNode:
                                        if (param.ParameterType == typeof(LatticeNode))
                                        {
                                            if (node.Ports.ContainsKey(portName))
                                            {
                                                throw new Exception(
                                                    $"ICE: FunctionIRNode should not have port of type LatticeNode. Value is passed implicitly. [{fNode}]");
                                            }

                                            emit.Ldarg(argumentExecutionIdx); // Load arg 0 for GetLatticeNode
                                            emit.Ldc_I4(nodeIdx); // Load arg 1 for GetLatticeNode
                                            emit.Call(typeof(ILGeneration).GetMethod(nameof(GetLatticeNode))); // Get the LatticeNode for the IRNode.
                                            // The LatticeNode reference is now on the stack.
                                        }
                                        // Parameters of type EntityManager are passed implicitly here:
                                        else if (param.ParameterType == typeof(EntityManager))

                                        {
                                            if (node.Ports.ContainsKey(portName))
                                            {
                                                throw new Exception(
                                                    $"ICE: FunctionIRNode should not have port of type EntityManager. Value is passed implicitly. [{fNode}]");
                                            }

                                            emit.Ldarg(argumentEntityManagerIdx); // Load the EntityManager passed into this function.
                                        }
                                        // Disconnected optional port. 
                                        else if (param.IsOptional && node.Ports[portName].Inputs.Count == 0)
                                        {
                                            Assert.IsFalse(fNode.NullableLiftedPorts.Contains(portName)); // Disconnected optional ports can't be nullable lifted.
                                            Assert.IsFalse(param.ParameterType.IsByRef); // No defaults for ref parameters
                                            Assert.IsTrue(node.Ports[portName].IsOptional); // Sanity check on the port type.

                                            // Build the default value as a constant, directly on the stack.
                                            // This is how C# does it. The parameter default is constructed in the calling method, 
                                            // not in the callee.
                                            EmitOptionalParamConstant(emit, param.ParameterType, param.DefaultValue);
                                        }
                                        // All other parameters are loaded from inputs.
                                        else
                                        {
                                            IRPort port = node.Ports[portName];
                                            if (port.Inputs.Count > 1)
                                            {
                                                throw new Exception(
                                                    $"More than one input [{port.Inputs.Count}] on a port is not allowed on FunctionIRNodes. [{fNode.Method}]");
                                            }

                                            if (port.Inputs.Count == 0)
                                            {
                                                Assert.IsFalse(param.IsOptional);
                                                throw new Exception($"No input connected on port [{portName}]. [{fNode}]");
                                            }

                                            IRNode inputNode = port.Inputs[0];
                                            
                                            // The type of the input value on the stack. This updates as we unbox/unwrap and apply various input coercions.
                                            Type inputType = compilation.CompileNode(inputNode).OutputType;

                                            // Load the value of the input node onto the stack.
                                            Local inputTmp = emit.DeclareLocal(inputType, "input");
                                            EmitReadNodeValue(inputNode, latticeIdx, inputTmp, exceptionValue, skipFunctionExecution);
                                            emit.Ldloc(inputTmp);

                                            // List<T> is passed as a NativeArray for now.
                                            // CollectIRNodes store their values as .NET Lists for GC, but we pass them as a native array.
                                            if (inputType.IsGenericType && inputType.GetGenericTypeDefinition() == typeof(List<>))
                                            {
                                                Assert.IsTrue(inputNode is CollectIRNode);
                                                Type elementType = inputType.GetGenericArguments()[0];
                                                emit.Call(typeof(ILGeneration).GetMethod(nameof(CreateTempNativeArray))!.MakeGenericMethod(elementType));
                                                inputType = typeof(NativeArray<>).MakeGenericType(elementType);
                                            }

                                            // If the input is of type T and the parameter is of type T?, we need to wrap the input in a nullable.
                                            if (param.ParameterType.IsNullable() && inputType == param.ParameterType.GetGenericArguments()[0])
                                            {
                                                emit.Newobj(param.ParameterType.GetConstructor(new[] { inputType }));
                                                inputType = param.ParameterType;
                                            }

                                            // If the port is nullable-lifted, emit a check for the input being null.
                                            // If it's null, we push null onto the stack, and skip the entire remainder of execution.
                                            // That's our result value. Otherwise, we unwrap it onto the stack.
                                            if (fNode.NullableLiftedPorts.Contains(portName))
                                            {
                                                Assert.IsTrue(!param.ParameterType.IsNullable());
                                                Assert.IsTrue(inputType.IsNullable());
                                                Assert.IsTrue(executionOutputType.IsNullable());

                                                Type nullableInnerType = inputType.GetGenericArguments()[0];

                                                Local tempInput = emit.DeclareLocal(inputType);
                                                emit.Stloc(tempInput);
                                                emit.Ldloca(tempInput); // Load a pointer to the nullable value.
                                                emit.Call(inputType.GetMethod("get_HasValue", BindingFlags.Public | BindingFlags.Instance)); // Invoked the bool Nullable.HasValue property.

                                                // Check if the input is non-null. If so, skip the next bit of code, to a few lines below.
                                                Label valueIsNotNull = emit.DefineLabel("valueIsNotNull");
                                                emit.Ldc_I4(true ? 1 : 0);
                                                emit.Beq(valueIsNotNull);

                                                // Load null into the output value local and skip to end of execution.
                                                emit.Ldloca(outputValue); // Load the address of the tmp value.
                                                emit.Initobj(executionOutputType); // Load 'null' into the tmp value.
                                                emit.Br(skipFunctionExecution); // Skip the remaining input loads, straight to the end of the node execution.

                                                // The place we'll jump if the input is *not* null. It has a value, unwrap the nullable.
                                                emit.MarkLabel(valueIsNotNull);

                                                emit.Ldloca(tempInput);
                                                emit.Call(inputType.GetMethod("get_Value", BindingFlags.Public | BindingFlags.Instance));

                                                // The unwrapped nullable is now on the stack.
                                                inputType = nullableInnerType;
                                            }

                                            // If the function takes a reference, we need to load the final value into a local variable
                                            // first to pass it as a reference. 
                                            if (param.ParameterType.IsByRef && inputType.IsGenericType && inputType.GetGenericTypeDefinition() == typeof(LatticeState.Wrapper<>))
                                            {
                                                // The input value on the stack should be a heap allocated wrapper class around a value.
                                                // Pull out a reference to that value and put it on the stack.
                                                Assert.AreEqual(inputType.GetGenericArguments()[0].MakeByRefType(), paramLocal.Type);

                                                FieldInfo objField = inputType.GetField("Obj");
                                                Assert.AreEqual(objField.FieldType, paramLocal.Type.GetElementType());

                                                // Load the address of the inner value onto the stack.
                                                emit.Ldflda(objField);

                                                inputType = objField.FieldType.MakeByRefType();
                                            }
                                            // Note: We don't currently support auto-casting from value type to reference. We could, but 
                                            // I'm not sure that's valuable. The IR should be well formed, and so far doesn't need it.
                                            else if (param.ParameterType.IsByRef && !inputType.IsByRef)
                                            {
                                                throw new NotImplementedException("ICE: We don't support conversion of value types to references." +
                                                                                  $"[{param.ParameterType}][{inputType}]");
                                            }

                                            // The input value is now on the stack. 
                                            Assert.AreEqual(param.ParameterType, inputType);
                                        }

                                        // We have our final parameter value, suitable for passing into the call invocation.
                                        // Store it into a local variable. We load it below when calling the function.
                                        emit.Stloc(paramLocal);
                                        parmeterLocals.Add(paramLocal);
                                    }

                                    // Loads the function parameters (inputs) from the stored variables.
                                    foreach (Local paramLocal in parmeterLocals)
                                    {
                                        emit.Ldloc(paramLocal);
                                    }

                                    // Call the actual method stored in the FunctionIRNode
                                    emit.Call(fNode.Method);

                                    // If the method return type is void, load a unit value onto the stack as the real return value.
                                    Type callReturnType = fNode.Method.ReturnType;
                                    if (callReturnType == typeof(void))
                                    {
                                        Assert.IsTrue(executionOutputType == typeof(Unit) || executionOutputType == typeof(Nullable<>).MakeGenericType(typeof(Unit)));
                                        callReturnType = typeof(Unit);
                                        Local temp = emit.DeclareLocal(typeof(Unit));
                                        emit.Ldloca(temp);
                                        emit.Initobj(typeof(Unit));
                                        emit.Ldloc(temp);
                                    }

                                    // If we have a valid output value, and the node is nullable lifted, we need to wrap the final value in a nullable.
                                    // Skip this step if the node already outputs a nullable (don't double nest nullables).
                                    if (fNode.NullableLiftedPorts.Count > 0 && !callReturnType.IsNullable())
                                    {
                                        // We use the callReturnType because the real method return type may be replaced by Unit.
                                        Assert.IsTrue(callReturnType.IsValueType);
                                        Type nullableValueType = typeof(Nullable<>).MakeGenericType(callReturnType);
                                        Assert.AreEqual(executionOutputType, nullableValueType);
                                        emit.Newobj(nullableValueType.GetConstructor(new[] { callReturnType })); // Create a new nullable object on the stack. This will consume the output of Call above.
                                    }
                                    // We have a valid output value, now on the stack.
                                    break;
                                }
                                case PreviousIRNode prevNode:
                                {
                                    // Load the default value into a temp local.
                                    IRNode defaultValueInput = prevNode.GetInput(PreviousIRNode.DefaultValuePort);
                                    Type defaultValueType = compilation.CompileNode(defaultValueInput).OutputType;
                                    Local defaultValueLocal = emit.DeclareLocal(defaultValueType, "defaultValue");
                                    EmitReadNodeValue(defaultValueInput, latticeIdx, defaultValueLocal, exceptionValue, skipFunctionExecution);

                                    // Setup arguments for the previous value handler.  (GetPreviousValue)
                                    emit.Ldarg(argumentExecutionIdx); // Load the ExecutionContext as arg0
                                    emit.Ldc_I4(compilation.Graph.NodeIndices[prevNode.BackRef.Node]); // Load the backref node index as arg1 
                                    emit.Ldloc(latticeEntity); // Load the lattice entity for arg2. May be Entity.Null.

                                    // Load the default value for arg3.
                                    // If the defaultValue is of type T and the parameter is of type T?, we need to wrap the defaultValue in a nullable.
                                    emit.Ldloc(defaultValueLocal);
                                    Type defaultValuePortType = prevNode.Ports[PreviousIRNode.DefaultValuePort].Type;
                                    if (defaultValuePortType.IsNullable() && defaultValueType == defaultValuePortType.GetGenericArguments()[0])
                                    {
                                        emit.Newobj(defaultValuePortType.GetConstructor(new[] { defaultValueType }));
                                        defaultValueType = defaultValuePortType;
                                    }

                                    Assert.AreEqual(defaultValueType, defaultValuePortType);

                                    // Call GetPreviousValue. Returns the value.
                                    emit.Call(typeof(ILGeneration).GetMethod(nameof(GetPreviousValue))!.MakeGenericMethod(executionOutputType));
                                    break;
                                }
                                case StateRefIRNode stateNode:

                                    // Load the default value into a temp local.
                                    IRNode defaultValInput = stateNode.GetInput(StateRefIRNode.DefaultValuePort);
                                    Type defaultValType = compilation.CompileNode(defaultValInput).OutputType;
                                    Local defaultValLocal = emit.DeclareLocal(defaultValType, "defaultValue");
                                    EmitReadNodeValue(defaultValInput, latticeIdx, defaultValLocal, exceptionValue, skipFunctionExecution);

                                    // Setup arguments for the state ref value handler.  (GetStateRef)
                                    emit.Ldarg(argumentExecutionIdx); // Load the ExecutionContext as arg0
                                    emit.Ldc_I4(compilation.Graph.NodeIndices[stateNode]); // Load the backref node index as arg1 
                                    emit.Ldloc(latticeEntity); // Load the lattice entity for arg2. May be Entity.Null.

                                    // Load the default value for arg3.
                                    // If the defaultValue is of type T and the parameter is of type T?, we need to wrap the defaultValue in a nullable.
                                    emit.Ldloc(defaultValLocal);
                                    Type stateValueType = stateNode.Ports[StateRefIRNode.DefaultValuePort].Type;
                                    if (stateValueType.IsNullable() && defaultValType == stateValueType.GetGenericArguments()[0])
                                    {
                                        emit.Newobj(stateValueType.GetConstructor(new[] { defaultValType }));
                                        defaultValType = stateValueType;
                                    }

                                    Assert.AreEqual(defaultValType, stateValueType);

                                    // Call GetStateRef. Returns the value.
                                    emit.Call(typeof(ILGeneration).GetMethod(nameof(GetStateRef))!.MakeGenericMethod(stateValueType));

                                    break;
                                case QualifierTransformIRNode qNode:
                                {
                                    Assert.IsTrue(qNode.CheckExceptions); // QTransforms must check exceptions, because we throw if the entity reference is invalid.

                                    // get the value of the input but at the qualifier provided by input 2.
                                    // If no qualifier is hooked, just uses the qualifier from the input.
                                    IRNode qInput = qNode.GetInput(QualifierTransformIRNode.PortQualifier, true);
                                    IRNode qValue = qNode.GetInput(QualifierTransformIRNode.PortInput);

                                    // If the qualifier input is hooked up, we use that entity instead of the default.
                                    Local entityIdxToLoadFrom;
                                    Metadata valueCompileData = compilation.CompileNode(qValue);
                                    if (!valueCompileData.Qualifier.HasValue)
                                    {
                                        // If the node we're referencing is not on a lattice, we don't need to provide an index.
                                        entityIdxToLoadFrom = null;
                                    }
                                    else if (qInput != null)
                                    {
                                        // If the node we're referencing is on a lattice, and the user provided a specific entity.
                                        Assert.IsTrue(compileData.Qualifier.HasValue);
                                        Assert.IsTrue(valueCompileData.Qualifier.HasValue);

                                        // Load the entity returned on the qualifier input into a local var.

                                        // Read the entity the user passed to this node.
                                        Local qInputEntity = emit.DeclareLocal(typeof(Entity), "qualifierInputEntity");
                                        EmitReadNodeValue(qInput, latticeIdx, qInputEntity, exceptionValue, skipFunctionExecution);

                                        // Map the requested entity to the lattice index for the input node value.
                                        Local idxLocal = emit.DeclareLocal(typeof(int), "entityIdxToLoadFrom");
                                        emit.Ldarg(argumentExecutionIdx); // Load IRExecutionContext as arg0
                                        emit.Ldc_I4(compilation.Graph.NodeIndices[qValue]); // Load the value node index as arg1.
                                        emit.Ldloc(qInputEntity); // Load the qInput entity value as arg2.
                                        emit.Call(typeof(ILGeneration).GetMethod(nameof(LookupLatticeIndex)));
                                        emit.Stloc(idxLocal); // Store the mapped index into our local.

                                        entityIdxToLoadFrom = idxLocal;
                                    }
                                    else
                                    {
                                        // Retrieve the value at the natural entity of this lattice.
                                        entityIdxToLoadFrom = latticeIdx;
                                    }

                                    // Load the value onto the stack, via a tmp local.
                                    Local referencedValue = emit.DeclareLocal(executionOutputType, "tmp");
                                    EmitReadNodeValue(qValue, entityIdxToLoadFrom, referencedValue, exceptionValue, skipFunctionExecution);
                                    emit.Ldloc(referencedValue);
                                    break;
                                }
                                case EntityIRNode:
                                    // Load the lattice entity. That's it!
                                    emit.Ldloc(latticeEntity);
                                    break;
                                case CollectIRNode:
                                {
                                    // Loop through all inputs and stuff them in an array.
                                    List<IRNode> inputs = node.Ports[CollectIRNode.PortInputs].Inputs;
                                    Type collectType = node.Ports[CollectIRNode.PortInputs].Type;

                                    // calculate number of inputs that are non null, or use a List<T>
                                    // emit a null branching operator.
                                    // roughly generate:
                                    // vals = new();
                                    // if (inputNodeValA != null) { vals.Add(inputNodeValA.Value} }
                                    // if (inputNodeValB != null) { vals.Add(inputNodeValB.Value} }
                                    // (but only if the input type of the collect is T and input is Nullable<T>)

                                    Type listType = typeof(List<>).MakeGenericType(collectType);
                                    Local tmpList = emit.DeclareLocal(listType);

                                    // todo: Allocation. We need to remove this.
                                    // Create a new List<T> to hold the intermediate list. (todo: allocates)
                                    // Note: This isn't a constant-sized array because nullable lifting may skip an input.
                                    emit.Newobj(listType.GetConstructor(new Type[] { }));
                                    emit.Stloc(tmpList); // Store it to a temp.

                                    // Set each index of the array to the value of each input.
                                    for (int i = 0; i < inputs.Count; i++)
                                    {
                                        Type inputType = compilation.CompileNode(inputs[i]).OutputType;
                                        Local tmpInputValue = emit.DeclareLocal(inputType, "tmpInput");
                                        
                                        // Load the input value into a tmp. If any are exceptions, skip to exception handler.
                                        EmitReadNodeValue(inputs[i], latticeIdx, tmpInputValue, exceptionValue, skipFunctionExecution);

                                        // If the value is Nullable<T> where T is the type of this collect node.
                                        Type nullableInputType = typeof(Nullable<>).MakeGenericType(collectType);
                                        if (inputType == nullableInputType)
                                        {
                                            Label skipNullable = emit.DefineLabel("skipNullableCollectInput");

                                            // Check for null, skip if so.
                                            emit.Ldloca(tmpInputValue);
                                            emit.Call(nullableInputType.GetProperty("HasValue").GetMethod);
                                            emit.Brfalse(skipNullable);

                                            // Store it to the array.
                                            emit.Ldloc(tmpList); // Load the list instance pointer.
                                            emit.Ldloca(tmpInputValue); // Load the value (1)
                                            emit.Call(nullableInputType.GetProperty("Value").GetMethod); // Load the value (2)
                                            emit.Call(listType.GetMethod("Add", BindingFlags.Public | BindingFlags.Instance));

                                            emit.MarkLabel(skipNullable);
                                        }
                                        // Normal values are simply added.
                                        else
                                        {
                                            // Store it to the array.
                                            emit.Ldloc(tmpList); // Load the list instance pointer.
                                            emit.Ldloc(tmpInputValue); // Load the value (1)
                                            emit.Call(listType.GetMethod("Add", BindingFlags.Public | BindingFlags.Instance));
                                        }
                                    }

                                    emit.Ldloc(tmpList); // Load the array onto the stack as the return value of this node.
                                    break;
                                }
                                case MalformedIRNode:
                                    // Malformed nodes should just be handled above like any other node with a valid CompilationError.
                                    throw new Exception($"Malformed nodes should never generate code. [{node}]");
                                default:
                                    throw new Exception($"Node type [{node.GetType()}] is not supported by compilation. [{node}]");
                            }

                            // After executing, all IRNodes leave a single value on the stack. Store it into the local.
                            emit.Stloc(outputValue);
                        }

                        executionEmitted.Add(node);

                        // This is the place nodes skip to when they want to exit early from their execution.
                        // There should be a valid outputValue or exceptionValue at this point.
                        emit.MarkLabel(skipFunctionExecution);

                        if (node.CheckExceptions)
                        {
                            Label finishTryBlock = emit.DefineLabel("finishTryBlock");

                            // Exception handling: Catch any exceptions thrown by the node, and store it into the local instead.
                            // We return exceptions as the output of the node.
                            // BeginCatchBlock automatically inserts a Leave instruction for the try block.
                            emit.BeginCatchBlock(typeof(Exception));

                            // In a catch block, the exception will be on the top of the stack.
                            emit.Stloc(exceptionValue);

                            // EndExceptionBlock automatically inserts a Leave instruction.
                            emit.EndExceptionBlock(); // End our 'try' block opened at the top. 
                            emit.MarkLabel(finishTryBlock);
                        }

                        // For local vars, store both output and exception into lattice.
                        emit.Ldloc(outputValue);
                        EmitStoreIntoLatticedLocal(node, latticedOutputs, latticeIdx);

                        emit.Ldloc(exceptionValue);
                        EmitStoreIntoLatticedLocal(node, latticedExceptions, latticeIdx);

                        // Store node outputs into debug database. 
                        emit.Ldarg(argumentExecutionIdx); // Load the IRExecution as arg1.
                        emit.Ldc_I4(nodeIdx); // Load the node index as arg 2.
                        emit.Ldloc(latticeEntity); // Load the entity (or Entity.Null) as arg3.
                        emit.Ldloc(outputValue); // Load the outputValue (or `default`) as arg4.
                        emit.Ldloc(exceptionValue); // Load the exceptionValue (or null) as arg5.
                        emit.Call(typeof(ILGeneration).GetMethod(nameof(DebugNodeExecution)).MakeGenericMethod(executionOutputType));

                        // Check the node's output for errors and log them.
                        emit.Ldarg(argumentExecutionIdx); // Load the IRExecution as arg1.
                        emit.Ldc_I4(nodeIdx); // Load the node index as arg 2.
                        emit.Ldloc(latticeEntity); // Load the entity (or Entity.Null) as arg3.
                        emit.Ldloc(exceptionValue); // Load the exceptionValue (or null) as arg4.
                        emit.Call(typeof(ILGeneration).GetMethod(nameof(LogNodeErrors)));

                        // If the node is needed in the next frame, write it to the entity's state.
                        if (compilation.Graph.ReferencedByPreviousNode.Contains(node))
                        {
                            emit.Ldarg(argumentExecutionIdx); // Load the IRExecution as arg1.
                            emit.Ldc_I4(nodeIdx); // Load the node index as arg 2.
                            emit.Ldloc(latticeEntity); // Load the entity (or Entity.Null) as arg3.
                            emit.Ldloc(outputValue); // Load the outputValue (or `default`) as arg4.
                            emit.Ldloc(exceptionValue); // Load the exceptionValue (or null) as arg5.
                            emit.Call(typeof(ILGeneration).GetMethod(nameof(StoreNodeIntoEcsState)).MakeGenericMethod(executionOutputType));
                        }

                        // Finish the loop if we're in a lattice.
                        if (compileData.Qualifier.HasValue)
                        {
                            // Increment index counter.
                            emit.Ldloca(latticeIdx);
                            emit.Call(typeof(ILGeneration).GetMethod(nameof(IncrementCounter)));

                            // If we got here, jump back to the top to see if we have any more entities to evaluate.
                            emit.Br(latticeLoopStart);

                            // The end of the loop. Jumps here if we have no more entities in the lattice.
                            emit.MarkLabel(latticeLoopEnd);
                        }

                        // We're finished with the node. If it's accessed in a later phase, store it's local buffer in the global store.
                        if (compilation.GetReferencedByAnotherWorkUnit().Contains(node))
                        {
                            EmitStoreCrossPhaseLocal(node, latticedOutputs, 0);
                            EmitStoreCrossPhaseLocal(node, latticedExceptions, 1);
                        }

                        // Emit profile marker end.
                        if (compilation.ProfileMarkerOptions != ProfileMarkerGranularity.None)
                        {
                            // Load the profiler marker for this node execution.
                            emit.Ldarg(argumentExecutionIdx);
                            emit.Ldfld(typeof(IRExecution).GetField(nameof(IRExecution.ProfilerMarkers)));
                            emit.Ldc_I4(nodeIdx);
                            emit.Ldelema(typeof(ProfilerMarker));

                            // Call the End method.
                            emit.Call(typeof(ProfilerMarker).GetMethod(nameof(ProfilerMarker.End), Type.EmptyTypes));
                        }
                    }
                    catch (Exception e)
                    {
                        Debug.LogError($"ICE: IL failed to generate for node [{node}]. Stacktrace:\n {e.StackTrace}");
                        throw new Exception($"ICE: IL failed to generate for node [{node}].", e);
                    }
                }

                emit.Ret();

                return true;
            }
            catch (Exception e)
            {
                Debug.LogException(e);
                return false;
            }
        }

        /// <summary>Loads the compile error exception for a node.</summary>
        public static Exception LoadCompilationError(IRExecution execution, int nodeIdx)
        {
            IRNode node = execution.Compilation.Graph.Nodes[nodeIdx];
            Metadata compileData = execution.Compilation.CompileNode(node);
            if (compileData.CompilationError == null)
            {
                throw new Exception("ICE: Node has no compilation error. [{node}]");
            }
            return compileData.CompilationError;
        }

        /// <summary>Gets the list of entities for the given qualifier.</summary>
        public static UnsafeList<Entity> LoadEntityList(IRExecution execution, string qualifierGuid)
        {
            Qualifier q = new(qualifierGuid);
            return execution.EntitiesByQualifier[q];
        }

        // Checks if the given exception is null, and if so, converts it to a InputNodeException and stores it in the output exception.
        // We use this helper to simplify branches and checks in the emitted IL.
        public static bool CheckInputException(IRExecution execution, int nodeIdx, Exception e, ref Exception exceptionLocal)
        {
            if (e != null)
            {
                if (e is not InputNodeException)
                {
                    IRNode node = execution.Compilation.Graph.Nodes[nodeIdx];
                    exceptionLocal = new InputNodeException(node, e);
                    return true;
                }
            }

            return false;
        }

        /// <summary>Gets the LatticeNode that created a specific IRNode.</summary>
        /// <remarks>This returns the *same* LatticeNode for all instances of a subgraph!</remarks>
        public static LatticeNode GetLatticeNode(IRExecution execution, int nodeIdx)
        {
            IRNode node = execution.Compilation.Graph.Nodes[nodeIdx];
            
            if (execution.Compilation.Graph.GetOwner(node) is not {} authoredNode)
            {
                throw new Exception($"ICE: Node has no authored node! [{node}]");
            }

            return authoredNode.Last;
        }

        /// <summary>Returns the T or List<T> local value from out cross phase local storage, onto the stack.</summary>
        public static object LoadCrossPhaseLocal(IRExecution execution, int nodeIdx, int pool)
        {
            var node = execution.Compilation.Graph.Nodes[nodeIdx];

            return pool switch
            {
                0 => execution.CrossPhaseOutputLocals[node],
                1 => execution.CrossPhaseExceptionLocals[node],
                _ => throw new ArgumentOutOfRangeException(nameof(pool), pool, null)
            };
        }

        /// <summary>Stores the given output local (T or List<T>) into the cross phase storage for this node.</summary>
        public static void StoreCrossPhaseLocal(IRExecution execution, int nodeIdx, int pool, object localval)
        {
            var node = execution.Compilation.Graph.Nodes[nodeIdx];

            switch (pool)
            {
                case 0:
                    execution.CrossPhaseOutputLocals[node] = localval;
                    return;
                case 1:
                    execution.CrossPhaseExceptionLocals[node] = localval;
                    return;
                default:
                    throw new ArgumentOutOfRangeException(nameof(pool), pool, null);
            }
        }

        /// <summary>Returns the value stored in the graph for the previous frame.</summary>
        public static T GetPreviousValue<T>(IRExecution execution, int nodeIdx, Entity entity, T defaultValue)
        {
            IRNode node = execution.Compilation.Graph.Nodes[nodeIdx];

            if (!execution.StateDict.ContainsKey(entity))
            {
                // If this hits, is the entity missing a LatticeState component, even though its graph uses state?
                Debug.LogError($"ICE: State dictionary is required for entity. [{entity}][{node}]");
                return defaultValue;
            }

            // Load the value of this node, stored from the previous frame's execution.
            if (execution.StateDict[entity].TryGetValue(node.Id, out object value))
            {
                if (value == null && typeof(T).IsNullable())
                {
                    return default; // null
                }

                if (value is T tValue)
                {
                    return tValue;
                }

                if (value is Exception)
                {
                    // todo: This fires if an Exception is propagated through state, because we don't differentiate
                    // output exceptions and exceptions in the state dictionary. This method should support piping
                    // an exception through, or (perhaps better) exceptions thrown shouldn't be written to state.
                    Debug.LogWarning($"Node threw exception in previous frame. Using default. [{node}][{typeof(T)}][{value?.GetType()}");
                }
                else
                {
                    Debug.LogWarning($"State was wrong type after Lattice hotswap. Using default. [{node}][{typeof(T)}][{value?.GetType()}");
                }
            }

            return defaultValue;
        }

        /// <summary>
        ///     Returns a pointer reference to stored state for a node. This is similar to GetPreviousValue, but more
        ///     efficient when you want to modify state.
        /// </summary>
        public static LatticeState.Wrapper<T> GetStateRef<T>(IRExecution execution, int nodeIdx, Entity entity, T defaultValue)
        {
            IRNode node = execution.Compilation.Graph.Nodes[nodeIdx];
            Assert.IsTrue(node is StateRefIRNode);

            // Load a reference to the stored state for this node.
            LatticeState latticeState = execution.StateDict[entity];
            if (latticeState.TryGetWrapper(node.Id, out LatticeState.Wrapper<T> value))
            {
                return value;
            }

            // Insert the default value, and return a reference to it.
            latticeState.SetValue(node.Id, defaultValue);
            latticeState.TryGetWrapper(node.Id, out LatticeState.Wrapper<T> v);
            return v;
        }

        /// <summary>
        ///     Looks up the lattice index of the given entity, under the given node's lattice. This is used for Qualifier
        ///     Transforms to do random access in a lattice.
        /// </summary>
        public static int LookupLatticeIndex(IRExecution execution, int nodeIdx, Entity qualifier)
        {
            IRNode node = execution.Compilation.Graph.Nodes[nodeIdx];

            Qualifier? qualifierId = execution.Compilation.CompileNode(node).Qualifier;

            if (!qualifierId.HasValue)
            {
                throw new Exception($"ICE: Node is not on a lattice. Should not call LookupLatticeIndex. [{node}]");
            }

            if (!execution.EntityToLatticeIndex[qualifierId.Value].TryGetValue(qualifier, out int latticeIdx))
            {
                if (qualifier == Entity.Null)
                {
                    throw new Exception($"ICE: The node [{node}] does not exist for at the global qualifier [{qualifier}].");
                }

                throw new Exception($"The node [{node}] does not exist for this entity [{qualifier}].");
            }

            return latticeIdx;
        }

        // Retrieves a scratch buffer that can be used to place output values of nodes in. 
        // Set pullFromExceptionPool to true, to retrieve a buffer from the exception list pool. 
        public static List<T> GetCachedLatticedList<T>(IRExecution execution, int nodeIdx, int pool)
        {
            IRNode node = execution.Compilation.Graph.Nodes[nodeIdx];
            Metadata compileData = execution.Compilation.CompileNode(node);

            IDictionary<IRNode, IList> listPool = pool switch
            {
                0 => execution.NodeOutputLists,
                1 => execution.NodeOutputExceptionLists,
                _ => throw new ArgumentOutOfRangeException(nameof(pool), pool, null)
            };

            // Create the list if it doesn't exist.
            List<T> list;
            if (listPool.TryGetValue(node, out IList outputList))
            {
                list = (List<T>)outputList;
            }
            else
            {
                list = new List<T>();
                listPool[node] = list;
            }

            // Fill the list with default values, if it's empty.
            if (list.Count == 0)
            {
                int entityCount = execution.EntitiesByQualifier[compileData.Qualifier!.Value].Length;
                for (int i = 0; i < entityCount; i++)
                {
                    list.Add(default);
                }
            }

            return list;
        }

        /// <summary>
        ///     An enumerator function called by the above executor. It iterates through the list of entities associated with
        ///     a node. It returns true if there's another entity to evaluate, and false if none are left. You can think of this
        ///     like a while loop.
        /// </summary>
        /// <param name="execution">Execution.</param>
        /// <param name="nodeIdx">Index of the node we're evaluating.</param>
        /// <param name="entityIdx">The current index of our loop through the entities.</param>
        /// <param name="entity">The variable to set the next entity value into.</param>
        public static bool EnumerateLattice(UnsafeList<Entity> entities, int entityIdx, out Entity entity)
        {
            // IRNode node = execution.Graph.Nodes[nodeIdx];
            // Metadata compileData = execution.Graph.CompileNode(node);
            //
            // if (!compileData.Qualifier.HasValue)
            // {
            //     throw new Exception("ICE: Tried to execute node as part of a lattice, but node was global.");
            // }
            // UnsafeList<Entity> entities = execution.EntitiesByQualifier[compileData.Qualifier.Value];

            if (entityIdx >= entities.Length)
            {
                entity = Entity.Null;
                return false;
            }

            entity = entities[entityIdx];
            return true;
        }

        // Increments the given index.
        public static void IncrementCounter(ref int entityIdx)
        {
            entityIdx += 1;
        }

        // Converts a managed array to a temporary NativeArray. Used for Collect.
        public static NativeArray<T> CreateTempNativeArray<T>(List<T> inList) where T : struct
        {
            var arr = new NativeArray<T>(inList.Count, Allocator.Temp);
            for (int i = 0; i < inList.Count; i++)
            {
                arr[i] = inList[i];
            }
            return arr;
        }

        // Stores a node's value into the debug database, but only if it's marked for debugging.
        // We use a runtime check for debugging so that it can be turned on/off without a recompile, as lattice windows
        // open and close.
        public static void DebugNodeExecution<T>(IRExecution execution, int nodeIdx, Entity qualifier, T outputValue, [CanBeNull] Exception exceptionValue)
        {
            // If exceptionValue is non-null, outputValue will be `default`, because the node threw during execution.

            IRNode node = execution.Compilation.Graph.Nodes[nodeIdx];

            // Store the value in our debug DB so the UI can render it.
            if (execution.DebugData != null /* && execution.DebugData.NodeDebugFlags[nodeIdx] */)
            {
                // qualifier = execution.ReduceQualifiers(node, qualifier); // todo: I think this is unnecessary?
                execution.DebugData!.Values[(qualifier, node)] = (object)exceptionValue ?? outputValue;
                execution.DebugData!.NodesRunThisFrame[node] = 0;
            }

            // Uncomment this to log execution.
            // Debug.Log($"Executed [{node}] [{exceptionValue ?? outputValue}]");
        }

        // Logs a node's errors if it returned an exception. 
        public static void LogNodeErrors(IRExecution execution, int nodeIdx, Entity qualifier, Exception exceptionValue)
        {
            IRNode node = execution.Compilation.Graph.Nodes[nodeIdx];

            if (!node.DoNotLogErrors)
            {
                // Only log an error if the exception originated from this node. If the exception is InputNodeException
                // it originated from an earlier node in this node's input graph.
                if (exceptionValue != null && exceptionValue is not InputNodeException)
                {
                    Debug.LogError($"Lattice node error: [{node}:{qualifier}]", execution.Compilation.Graph.GetOwner(node)?.Root);
                    Debug.LogException(exceptionValue, execution.Compilation.Graph.GetOwner(node)?.Root);
                }
            }
        }

        // Stores the output value of a node into the ECS state for this entity. Necessary if this node is depended on
        // in the next frame. Entity qualifier can be Entity.Null if this node is global.
        public static void StoreNodeIntoEcsState<T>(IRExecution execution, int nodeIdx, Entity qualifier, T outputValue, Exception exceptionValue)
        {
            // todo(perf): Boxing. Will likely need state struct generation to avoid.
            IRNode node = execution.Compilation.Graph.Nodes[nodeIdx];

            if (exceptionValue != null)
            {
                execution.StateDict[qualifier].SetValue(node.Id, exceptionValue);
            }
            else
            {
                execution.StateDict[qualifier].SetValue(node.Id, outputValue);
            }
        }

        /// <summary>
        ///     Emits the given constant value as IL. This mirrors the constant emission process for default parameters in C#,
        ///     as determined via SharpLab. This is a little challenging, because we have to take a runtime object value and reduce
        ///     it down to IL instructions. Luckily, the set of constants in C# is rather limited, so it's not too complex.
        /// </summary>
        /// <remarks>This supports all C# types except decimal, nint, and nuint.</remarks>
        public static void EmitOptionalParamConstant(GroboIL emit, Type constantType, object constantValue)
        {
            if (constantType == typeof(decimal) || constantType == typeof(nint) || constantType == typeof(nuint))
            {
                throw new Exception($"Type not supported as optional parameter: [{constantType}].");
            }

            // This should cover all cases, although I suspect there may be missed logic.
            // The only type we don't support is 'decimal'.

            // Convert enums to their underlying integral type first.
            if (constantType.IsEnum)
            {
                Type underlyingType = Enum.GetUnderlyingType(constantType);
                object underlyingValue = Convert.ChangeType(constantValue, underlyingType);
                Assert.IsTrue(constantValue.GetType() == constantType || constantValue.GetType() == underlyingType);
                EmitOptionalParamConstant(emit, underlyingType, underlyingValue);
                return;
            }

            // Nullables either load (pass through), or they emit the constructor for their inner type and wrap it 
            // with a nullable. This is only supported for primitives in C#.
            if (constantType.IsNullable())
            {
                if (constantValue != null)
                {
                    Assert.IsFalse(constantType.IsPrimitive); // I don't think it's possible to define a non-null non-primitive optional default in C#.
                    Type innerType = constantType.GetGenericArguments()[0];
                    Assert.IsTrue(constantValue.GetType() == innerType // A boxed (object) nullable should be represented at runtime as its inner type.
                                  || innerType.IsEnum); // A nullable enum will have an inner value of the underlying type, weirdly enough. :\
                    EmitOptionalParamConstant(emit, innerType, constantValue);
                    emit.Newobj(constantType.GetConstructor(new[] { innerType }));
                    return;
                }
                // pass through to the value type handler.
            }

            // Primitive types that convert to I4 for IL.
            // (https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/integral-numeric-types)
            if (constantType == typeof(sbyte)
                || constantType == typeof(byte)
                || constantType == typeof(short)
                || constantType == typeof(ushort)
                || constantType == typeof(int)
                || constantType == typeof(uint)
                || constantType == typeof(char)
                || constantType == typeof(bool)) // bools are an I4, either 1 or 0.
            {
                emit.Ldc_I4(PrimitiveNumericToSignedInt(constantValue));
                return;
            }

            // Primitive types that convert to I8 for IL
            if (constantType == typeof(long) || constantType == typeof(ulong))
            {
                emit.Ldc_I8(PrimitiveNumericToSignedLong(constantValue));
                return;
            }

            if (constantType == typeof(float))
            {
                emit.Ldc_R4((float)constantValue!);
                return;
            }

            if (constantType == typeof(double))
            {
                emit.Ldc_R8((double)constantValue!);
                return;
            }

            if (constantType == typeof(string))
            {
                emit.Ldstr((string)constantValue!);
                return;
            }

            // For structs and tuples, we only support default. As far as I understand, this how it works in C#.
            // We can load the default simply by initobj'ing it.
            if (constantType.IsValueType)
            {
                if (constantValue != null)
                {
                    // Default is signified in ParameterInfo.DefaultValue with 'null'
                    throw new Exception("Struct and tuple types only support 'default' as their value in an optional parameter.");
                }

                Local tmpLocal = emit.DeclareLocal(constantType, "tmpConstant");
                emit.Ldloca(tmpLocal);
                emit.Initobj(constantType);
                emit.Ldloc(tmpLocal);
                return;
            }

            // Type must be a non-string reference type. Load null.
            if (constantValue != null)
            {
                throw new Exception($"Unsupported default parameter value: [{constantValue}].");
            }
            emit.Ldnull();
        }

        /// <summary>Converts a primitive numeric value to the representation used in IL. (ie. I4)</summary>
        private static int PrimitiveNumericToSignedInt(object o)
        {
            // Makes use of auto cast to int on return.
            // Weirdly enough casting o directly throws an exception. (ie. return (int)o)
            return o switch
            {
                bool b => b ? 1 : 0,
                sbyte sb => sb,
                byte b => b,
                short s => s,
                ushort us => us,
                int i => i,
                uint u => unchecked((int)u), // uint is loaded onto the stack as an int! weird.
                char c => c,
                _ => throw new Exception($"Unsupported type: [{o.GetType()}]")
            };
        }

        /// <summary>Converts a primitive numeric long value to the representation used in IL. (ie. I8)</summary>
        private static long PrimitiveNumericToSignedLong(object o)
        {
            // Makes use of auto cast to int on return.
            // Weirdly enough casting o directly throws an exception. (ie. return (int)o)
            return o switch
            {
                long l => l,
                ulong ul => unchecked((long)ul),
                _ => throw new Exception($"Unsupported type: [{o.GetType()}]")
            };
        }
    }
}
// @formatter:wrap_lines restore
